services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    networks:
      - dynadok_network
    ports:
      - ${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - dynadok_network
    volumes:
      - data:/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - dynadok_network
    volumes:
      - data:/var/lib/rabbitmq

networks:
  dynadok_network:
    driver: bridge
    name: dynadok_network

volumes:
  data:
